version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cms-service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - cms-network

volumes:
  redis-data:
    driver: local

networks:
  cms-network:
    driver: bridge
